server:
  port: 8083
spring:
  cloud:
    discovery:
      enabled: true
  application:
    name: billing-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/soa-realm/protocol/openid-connect/certs

logging:
  level:
    org:
      springframework:
        security: DEBUG
      keycloak: DEBUG
